export const CardData = [
  {
    icon: "https://i.postimg.cc/tT5hPKw1/calcum.png",
    profile: "Calum Lewis",
    picture: "https://i.postimg.cc/Z5dpjBXz/Pancake.png",
    name: "Pancake",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/WpydKpGN/Ellif.png",
    profile: "Eilif Sonas",
    picture: "https://i.postimg.cc/Wb6h4mR3/Salad.png",
    name: "Salad",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/Y2DFHzHw/Elena.png",
    profile: "Elena Shelby",
    picture: "https://i.postimg.cc/tJDQK4fX/Lasagne.png",
    name: "Lasagne",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/HWv6hMvr/John.png",
    profile: "John Priyadi",
    picture: "https://i.postimg.cc/wBDPKByS/Fruit-Salad.png",
    name: "Salad",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/WpydKpGN/Ellif.png",
    profile: "Eilif Sonas",
    picture: "https://i.postimg.cc/tJDQK4fX/Lasagne.png",
    name: "Salad",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/tT5hPKw1/calcum.png",
    profile: "Calum Lewis",
    picture: "https://i.postimg.cc/Z5dpjBXz/Pancake.png",
    name: "Pancake",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/WpydKpGN/Ellif.png",
    profile: "Eilif Sonas",
    picture: "https://i.postimg.cc/Wb6h4mR3/Salad.png",
    name: "Salad",
    description: "Food >60 mins",
  },
  {
    icon: "https://i.postimg.cc/HWv6hMvr/John.png",
    profile: "John Priyadi",
    picture: "https://i.postimg.cc/wBDPKByS/Fruit-Salad.png",
    name: "Salad",
    description: "Food >60 mins",
  },
];